add comments for visualize predictions (#151)
* Fix missing argument

* more import bugfixes (#126)

* fix missing attribute 'utils'

* removed import statements for unused modules

* add readme about config files (#129)

* readme about config files

* link to predefined script

* Update README.md

* Simplified install instructions (#127)

* Simpliefied install instructions

Multiple requirements files for different use cases.

* minor change to README

* minor change adding link to docs for build from source.

* update install instruction, add +cpu to torch requirements.txt

Co-authored-by: Benjamin Ummenhofer <benjaminum@gmail.com>

* added conditionals in requirements-torch for macos (#131)

* Fix color dictionary in Semantic-KITTI bgr -> rgb (#130)

* Enable hierarchy UI feature in visualizer for SemanticKITTI (#133)

* Import os (#148)

I am getting also another error later about 

NameError                                 Traceback (most recent call last)
<ipython-input-5-bed5d0e06c9a> in <module>
     22 pipeline_k.load_ckpt(model.cfg.ckpt_path)
     23 
---> 24 data_path = os.path.dirname(os.path.realpath(__file__)) + "/demo_data"
     25 pc_names = ["000700", "000750"]
     26 

NameError: name '__file__' is not defined


for this

data_path = os.path.dirname(os.path.realpath(__file__)) + "/demo_data"

* Create LICENSE

* add comments

Co-authored-by: Sanskar Agrawal <sanskaragrawal107@gmail.com>
Co-authored-by: Benjamin Ummenhofer <benjaminum@gmail.com>
Co-authored-by: YilingQiao <49262224+YilingQiao@users.noreply.github.com>
Co-authored-by: ssheorey <41028320+ssheorey@users.noreply.github.com>
Co-authored-by: Ignacio Vizzo <ignaciovizzo@gmail.com>
Co-authored-by: prewettg <prewettg@gmail.com>
Co-authored-by: Albhox <albertotono3@gmail.com>
Co-authored-by: germanros1987 <38517452+germanros1987@users.noreply.github.com>